version: '3'

services:
  db:
    image: postgres
    volumes:
      - db-django:/var/lib/postgresql/data:delegated
    ports:
      - 5432:5432
  web:
    build: . 
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
    volumes:
      - ./src:/app:delegated
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  db-django:
    external: false